### ISSUE TITLE
Nonexistent file crash in CMEMS.jl

### ISSUE THREAD

**Issue by paolo-oliveri** [gher-uliege/PhysOcean.jl#3]
Hello,
I found a bug in CMEMS.jl.
If all the content in index_history.txt does not match exactly what really is in the folders inside the function CMEMS.download will enter in a loop that starts in line 115 (catch err).
You can relax this catch by skipping non existent files or directories listed in index_history.txt.
Sincerely,
Paolo Oliveri

**Comment by Alexander-Barth** [comment]
Hi Paolo, thank you for reporting this issue. 
Can you try with the master version, to see if it fixes the issue? If  it does not, can you provide a minimal working code example to reproduce the issue?

Thanks,
Alex

**Comment by paolo-oliveri** [comment]
Hello Alex,
I downloaded your new CMEMS.jl file and the problem is still here.

You can try by entering this code:

CMEMS.download([-180 180], [0, 180], [DateTime(1900,1,1),DateTime(2018,12,31)], "TEMP", USER, PASS, FOLDER, indexURLs = ["ftp://my.cmems-du.eu/Core/INSITU_BAL_TS_REP_OBSERVATIONS_013_038/index_history.txt"])

There is a problem in the index_history.txt file that has a wrong folder to point files:

ftp://my.cmems-du.eu/Core/INSITU_BAL_NRT_OBSERVATIONS_013_032/

instead of

ftp://my.cmems-du.eu/Core/INSITU_BAL_TS_REP_OBSERVATIONS_013_038/

Then your script, instead of skipping the folder, goes into a download trying loop.

If you need more information please tell me

Sincerely,
Paolo Oliveri

**Comment by Alexander-Barth** [comment]
The download code tries 5 times and then goes to the next file. The download script tries multiple time because there could be a transient network issue. The proper fix is for CMEMS to correct the index_history.txt file if multiple files are affected.
